apiVersion: v1
kind: Pod
metadata:
  name: web-pod
  labels:
    app: web
spec:
  containers:
  - name: web
    image: kubedevio/web-color:green
    ports:
    - name: http
      containerPort: 80
      protocol: TCP
